CREATE TABLE "users" (
                         "id" BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
                         "email" varchar UNIQUE NOT NULL,
                         "password_hash" varchar NOT NULL,
                         "created_at" timestamptz,
                         "trust_score" float
);

CREATE TABLE "incidents" (
                             "id" BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
                             "user_id" bigint,
                             "latitude" double precision NOT NULL,
                             "longitude" double precision NOT NULL,
                             "category" varchar NOT NULL,
                             "severity_score" int NOT NULL,
                             "incident_time" timestamptz NOT NULL,
                             "reported_at" timestamptz NOT NULL,
                             "expires_at" timestamptz NOT NULL,
                             "is_visible" boolean NOT NULL DEFAULT true
);

CREATE TABLE "historical_data" (
                                   "id" BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
                                   "latitude" double precision NOT NULL,
                                   "longitude" double precision NOT NULL,
                                   "incident_time" timestamptz NOT NULL
);

ALTER TABLE "incidents" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;
